### ISSUE TITLE
Project Kanban Initialization

### ISSUE THREAD

**Issue by mmsesay** [Hector096/SpaceTraveller#97]
Hello, this React group project comprises two people (Myself and @Hector096)
We have set up the kanban  board and here is the link to the project board: https://github.com/Hector096/SpaceTraveller/projects/3

**Comment by arslanbisharat** [comment]
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [ ] There should be an equal distribution of cards between both team members. 
- [ ] Required categories:`Setup`, `Fetch data`, `Lists render`, `Actions`, `Conditional components`, `Filters`

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by mmsesay** [comment]
Thank you @arslanbisharat. We have assigned the tasks equally as required.

**Comment by omar-labana** [comment]
Hi @mmsesay and @Hector096 , 

Your project is complete!  There is nothing else to say other than... it's time to start your project!  👏
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by mmsesay** [comment]
Thanks for the review @omar-labana.
